# Generated by Django 4.0.1 on 2022-01-29 17:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField()),
                ('bug', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.bug')),
            ],
        ),
    ]
