# Generated by Django 4.0.1 on 2022-01-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_bug_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
